version: '3'
services:

  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - mysql
    environment:
      url: http://localhost
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: user1
      database__connection__password: password1
      database__connection__database: db
    volumes:
        - ../content:/var/lib/ghost/content
        
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    volumes:
      - ../mysql:/var/lib/mysql
    
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - ghost
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
